### ISSUE TITLE
Missing database .sql file 

### ISSUE THREAD

**Issue by Insaneshane99** [Midsetts/qb-mdt#1]
![image](https://user-images.githubusercontent.com/87678580/157343039-bd0d0c45-9f9d-478f-a1fe-a16ecf173c10.png)

**Comment by Insaneshane99** [comment]
go borrow the database from https://github.com/d-w00d/qb-mdt

**Comment by Midsetts** [comment]
> go borrow the database from https://github.com/d-w00d/qb-mdt

my bad buddy, i'll make sure to get it for you here soon

**Comment by Insaneshane99** [comment]
ive already got the database , im suggesting you add this for others
